export const projects = [
  {
    title: 'T.A.L.K.',
    description: "6 month capstone project with Invoca to create a full stack web app, providing call information in a single view. Produced an intuitive multi-cloud service, showing sales agents additional call information including important keywords, a summary, and sentiment analysis - obtained from near real-time call transcriptions",
      image: '/images/0.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    demo: 'https://youtu.be/qGD9hiCJQoY/',
    code: 'https://github.com/XuperBryan/T.A.L.K./',
    id: 0,
  },
  {
    title: 'My Memories',
    description: "Using the MERN tech stack, this basic social media app allows users to create, like, edit, and delete posts. Functionalities differ depending on ownership of post. Fully responsive website and includes authentication through google oauth or native user database.",
      image: '/images/1.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    demo: 'https://www.youtube.com/watch?v=MAZwwFAk7mM',
    code: 'https://github.com/XuperBryan/My-Memories',
    id: 0,
  },
  {
    title: 'Pacman AI',
    description:"Built Pacman AI with the capabilities to solve puzzles against two ghost computers. Implemented evaluation function and expectimax function as the ghosts had a 50% change to go in a random direction or go towards the player. Operates at a 70% success rate over a medium-sized map.",
    image: '/images/2.png',
    tags: ['Python'],
    demo: '',
    code: 'https://github.com/XuperBryan/Pacman_AI',
    id: 1,
  },
  {
    title: 'Chat With Me',
    description:"Built fully functional real-time chat app using React, GraphQL, and Node. Supports multiple chat rooms and concurrent users. Winner of \"Best React + GraphQL App\" Category at SB Hacks VIII.",
    image: '/images/7.jpg',
    tags: ['React', 'GraphQL', 'Node'],
    demo: 'https://youtu.be/BVzAhW2hG0M/',
    code: 'https://github.com/sbhacks-viii/chat-with-me',
    id: 2,
  },
  {
    title: 'Icebreaker Bot',
    description: "Created a Discord Bot using Discord.js. Functionalities include interactive music player, group icebreaker games, and urban dictionary lookup. Finalist in \"Best Beginner Hack\" Category at SB Hacks VII, and currently active in over 40 servers. ",
      image: '/images/3.jpg',
      tags: ['Discord.js'],
    demo: 'https://discord.com/oauth2/authorize?client_id=800069967894151178&scope=bot&permissions=3198016',
    code: 'https://github.com/XuperBryan/sbhacks7-icebreaker-bot',
    id: 3,
  },
  {
    title: 'DUAL',
    description: "Implemented 1-2 player game using Java Swing and Java Graphics. Created weak AI for single player mode. 2-D shooting game includes life bar, ammunition bar, as well as an aiming device.",
    image: '/images/4.png',
    tags: ['Java'],
    demo: '',
    code: 'https://github.com/XuperBryan/DUAL',
    id: 4,
  },
  {
    title: 'Coronavirus Classifier',
    description: "Created a Naive Bayes Classifier model on Coronavirus datasets. Trained to predict whether a given test subject would survive or pass away. Trained and validated using public datasets with 200,000+ data points. ",
    image: '/images/5.png',
    tags: ['C++'],
    demo: '',
    code: 'https://github.com/XuperBryan/Naive_Bayes_Classifier_AI',
    id: 5,
  },
  {
    title: 'Figma Conversion',
    description: "Created a modern style UI/UX design using a Figma template. Wrote CSS and frontend using React, and used media queries to make entire web app fully responsive. Currently filled with placeholder text, but learned a lot about positioning and styling through this Figma template conversion.",
    image: '/images/6.png',
    tags: ['React', 'Figma', 'CSS'],
    demo: 'https://figma-conversion.netlify.app/',
    code: 'https://github.com/XuperBryan/figma-magic',
    id: 6,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Took my first Computer Science class in Java', },
  { year: 2018, text: 'Admitted to UCSB under Math major, started process to transfer into Computer Science', },
  { year: 2019, text: 'Transferred into Computer Science major, learned C++ and Computer Science fundamentals', },
  { year: 2020, text: 'Learned AGILE methodology, team-based application development, and React frontend', },
  { year: 2021, text: 'Attended first hackathon, tutored CMPSC16 at UCSB, started building AI projects. Quantitative Analysis Researcher Intern at Prudential Financial ', },
  { year: 2022, text: 'Started creating and designing full stack web applications, won first hackathon, accepted into MS CS program at UCSB, Software Engineer Intern at Meta', },
];